version: "3"
services:
  node-app:
    container_name: express-node-app-container
    ports:
      - "80:80"
    env_file:
      - ./.env   
    # depends_on:
    #   - mongo    
#   mongo:
#     image: mongo
#     restart: always
#     volumes:
#       - mongo-db:/data/db 
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: root
#       MONGO_INITDB_ROOT_PASSWORD: example

# volumes:
#   mongo-db: